[package]
name = "dashmap"
version = "4.0.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/xacrimon/dashmap"
homepage = "https://github.com/xacrimon/dashmap"
description = "Blazing fast concurrent HashMap for Rust."
readme = "README.md"
documentation = "https://docs.rs/dashmap"
keywords = ["atomic", "concurrent", "hashmap"]
categories = ["concurrency", "algorithms", "data-structures"]

[dependencies]
once_cell = "1.3.1"

[dev-dependencies]
bustle = { git = "https://git.nebulanet.cc/Acrimon/bustle-temp-fix.git" }
fxhash = "0.2.1"
num_cpus = "1.12.0"
tracing-subscriber = "0.2.2"

[[bench]]
name = "dashmap"
harness = false
